-- HOST

DROP SEQUENCE IF EXISTS PUBLIC.SEQ_HOST_ID;
CREATE SEQUENCE	PUBLIC.SEQ_HOST_ID;

DROP TABLE IF EXISTS PUBLIC.HOST;
CREATE TABLE PUBLIC.HOST (
    HOST_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_HOST_ID) NOT NULL AUTO_INCREMENT,
	IP VARCHAR(255),
	IDENTITY VARCHAR(255),
	LOGIN VARCHAR(255),
	PASSWORD VARCHAR(255),
	PRIMARY KEY (HOST_ID)
);

-- DEVICE

DROP SEQUENCE IF EXISTS PUBLIC.SEQ_DEVICE_ID;
CREATE SEQUENCE	PUBLIC.SEQ_DEVICE_ID;

DROP TABLE IF EXISTS PUBLIC.DEVICE;
CREATE TABLE PUBLIC.DEVICE (
	DEVICE_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_DEVICE_ID) NOT NULL AUTO_INCREMENT,
	HOST_ID BIGINT NOT NULL,
	VENDOR VARCHAR(255),
	HARDWARE VARCHAR(255),
	SOFTWARE VARCHAR(255),
	PRIMARY KEY (DEVICE_ID),
	CONSTRAINT device_fk FOREIGN KEY (HOST_ID) REFERENCES HOST (HOST_ID) ON DELETE CASCADE
);

-- init test dataset
INSERT INTO PUBLIC.HOST (HOST_ID, IP, IDENTITY, LOGIN, PASSWORD)
VALUES (1, '10.0.0.1', 'host_1', 'login_1', 'password_1');

INSERT INTO PUBLIC.HOST (HOST_ID, IP, IDENTITY, LOGIN, PASSWORD)
VALUES (2, '10.0.0.2', 'host_2', 'login_2', 'password_2');

INSERT INTO PUBLIC.DEVICE (DEVICE_ID, HOST_ID, VENDOR, HARDWARE, SOFTWARE)
VALUES (1, 1, 'vendor_1', 'hardware_1', 'software_1');

INSERT INTO PUBLIC.DEVICE (DEVICE_ID, HOST_ID, VENDOR, HARDWARE, SOFTWARE)
VALUES (2, 2, 'vendor_2', 'hardware_2', 'software_2');

INSERT INTO PUBLIC.DEVICE (DEVICE_ID, HOST_ID, VENDOR, HARDWARE, SOFTWARE)
VALUES (3, 1, 'vendor_3', 'hardware_3', 'software_3');