DROP SEQUENCE IF EXISTS PUBLIC.SEQ_ID;
CREATE SEQUENCE	PUBLIC.SEQ_ID;

DROP TABLE IF EXISTS PUBLIC.HOSTS;
CREATE TABLE PUBLIC.HOSTS (
	ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SEQ_ID) NOT NULL AUTO_INCREMENT,
	DEVICE VARCHAR(255),
	IDENTITY VARCHAR(255),
	IP VARCHAR(255),
	LOGIN VARCHAR(255),
	PASSWORD VARCHAR(255),
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

-- init test dataset
INSERT INTO PUBLIC.HOSTS (ID,IP,IDENTITY,LOGIN,PASSWORD)
VALUES (1, '10.0.7.183/32','shved_nataljya','admin','120960');

INSERT INTO PUBLIC.HOSTS (ID,IP,IDENTITY,LOGIN,PASSWORD)
VALUES (2, '10.0.7.186/32','kurta_ivan','admin','120960');